### PR TITLE
changes from git tutorial account

### PR DESCRIPTION
**Pull request by git-tutorial-account**
i have completed my job after 20 months of working through MCO ! 
EAT THAT MAN !!!

### CODE REVIEW

**Comment by victor-tan-hk** [comment]
I really don't think you worked hard enough. You gotta work some more man !!!

**Comment by git-tutorial-account** [comment]
what in the world ??? How many hours do you want me to work on this stupid project anyway

**Comment by victor-tan-hk** [comment]
Ok lah give you chance lah.... consider this job finish

**Comment by victor-tan-hk** [comment]
i will close it now

**Pull request merged**
